### ISSUE TITLE
Migrate to league/flysystem-aws-s3-v3

### ISSUE THREAD

**Issue by voodoo-rocks** [creocoder/yii2-flysystem#12]
Does migrate to league/flysystem-aws-s3-v3 is planned? If no, will be this package work with league/flysystem-aws-s3-v3 package?

**Comment by iadj** [comment]
Just noticed the same issue, AWS S3 v2 is no longer supported generally, and yii2-flysystem doesn't yet support s3-v3. Is this project still being worked on?

**Comment by saada** [comment]
https://github.com/creocoder/yii2-flysystem/pull/16

**Comment by atiberius** [comment]
For the owner: please merge that pull request. I need the s3-v3 version.
Thank you!

**Comment by saada** [comment]
@creocoder <--- that would be him

**Comment by schmunk42** [comment]
@creocoder Ping...

**Comment by creocoder** [comment]
#16 was merged

**Comment by schmunk42** [comment]
A 0.9.0-beta1 release would also be nice.
