### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by schmunk42** [creocoder/yii2-flysystem#23]
Would be really helpful, since we need to include dev-master manually in many projects.

see also https://github.com/creocoder/yii2-flysystem/issues/12#issuecomment-278294362

Beta or RC would be sufficient.

**Comment by vstanchev** [comment]
+1

**Comment by schmunk42** [comment]
@creocoder Ping. Please put a tag on this.

**Comment by madsnedergaard** [comment]
Hey @creocoder, could you please help with this? It's such a quick fix - the package is kinda useless at until we can use v3 :(
**EDIT:**
For now I have switched to a fork (damianz/yii2-flysystem) that works with v3.

**Comment by creocoder** [comment]
Guys, sorry for delay with release. Done.
