### ISSUE TITLE
Отсутствует управление $directoryPerm в SftpAdapter

### ISSUE THREAD

**Issue by shastox** [creocoder/yii2-flysystem#25]
У SftpAdapter есть свойство $directoryPerm оно просто необходимо, чтобы управлять правами на папки.

Решение: 

В https://github.com/creocoder/yii2-flysystem/blob/master/src/SftpFilesystem.php необходимо добавить `	public $directoryPerm;` и в методе `prepareAdapter()` добавить в массив значение `'directoryPerm'` тогда в конфиге, к примеру 

```
'ftpFs' => [
            'class' => 'creocoder\flysystem\FtpFilesystem',
            'host' => 'ftp.example.com',
            // 'port' => 21,
            // 'username' => 'your-username',
            // 'password' => 'your-password',
            // 'ssl' => true,
            // 'timeout' => 60,
            // 'root' => '/path/to/root',
            // 'permPrivate' => 0700,
            // 'permPublic' => 0744,
            // 'passive' => false,
            // 'transferMode' => FTP_TEXT,
        ],

```
Мы сможем управлять $directoryPerm

**Comment by Sensetivity** [comment]
Seems this issue was solved.
