### ISSUE TITLE
Filesystem base class should implement League\Flysystem\FilesystemInterface

### ISSUE THREAD

**Issue by ndobromirov** [creocoder/yii2-flysystem#36]
It is working now, but the fact is that the the adapter is not compliant with the interface explicitly, so decoration can not be implemented easily.

**Comment by schmunk42** [comment]
You can get the base filesystem from the adapter since `0.9.1`, please let me know if this solves your issue.

**Comment by ndobromirov** [comment]
Well I was expecting the extension to have the component implement the interface directly, not through magic methods or member accessor. 

It's not something impossible to work-around. Consider this closable.

**Comment by schmunk42** [comment]
OK, I'll close this, if can come up with a PR, let us know.
