### ISSUE TITLE
Connection refused 

### ISSUE THREAD

**Issue by alfie-ciandt** [creocoder/yii2-flysystem#41]
I dont know where is wrong (cry)!   
![image](https://user-images.githubusercontent.com/27768327/56651505-bf8b3680-66bb-11e9-93b2-7d23cf64c4ba.png)

**Comment by schmunk42** [comment]
This looks like a problem on your system/network. Try to debug if you can get a connection to lan-storage........cn:443 with `curl` or `telnet`.
