### ISSUE TITLE
Asset manager S3 publish interface

### ISSUE THREAD

**Issue by comradefuzz** [creocoder/yii2-flysystem#43]
**Struggling to have my assets published to S3.** Asset manager relies on direct filesystem operations.

**Solution** Thought it would be covenient to have AssetManager which is capable to use flysystem as an abstraction to filesystem. Not sure if this feature will break S.O.L.I.D. but I don't see any reasonable places to make this happen.

**Comment by schmunk42** [comment]
I think this is out-of-scope for this library. You could create a `yii2-flysystem-asset-manager`, which depends on this lib.
