### ISSUE TITLE
DropboxFilesystem prepareAdapter is wrong

### ISSUE THREAD

**Issue by mikk150** [creocoder/yii2-flysystem#49]
I think
https://github.com/creocoder/yii2-flysystem/blob/1fdef0883316f891ecb512011cac462213156e38/src/DropboxFilesystem.php#L56

line is wrong, since `Spatie\Dropbox\Client` second parameter should be Guzzle client not prefix

It should probably be 
```php
        return new DropboxAdapter(
            new Client($this->token),
            $this->prefix
        );
```

**Comment by schmunk42** [comment]
Available in https://github.com/creocoder/yii2-flysystem/releases/tag/1.1.0
