### ISSUE TITLE
Local Filesystem defaults write flag LOCK_EX 

### ISSUE THREAD

**Issue by jcord04** [creocoder/yii2-flysystem#58]
By default Flysystem `League\Flysystem\Adapter\Local` sets the write flag to `LOCK_EX` which does not work with all storage types (e.g. my NFS does not support `LOCK_EX`). 

It would be ideal if these default arguments could be overridden in the Yii2 component, for example;

```
return [
    //...
    'components' => [
        //...
        'fs' => [
            'class' => 'creocoder\flysystem\LocalFilesystem',
            'path' => '@webroot/files',
            // 'writeFlags' => LOCK_EX,
            // 'linkHandling' => 0002,
            // 'permissions' => [], 
        ],
    ],
];
```

**Comment by jcord04** [comment]
Hi @schmunk42 thanks for merge, are we able to get this published to Packagist?

**Comment by schmunk42** [comment]
Just triggered a manual update, since I do not own the package on packagist.
You should be able to do this with a packagist account btw.

**Comment by jcord04** [comment]
Thanks @schmunk42, all working 👍
