### ISSUE TITLE
SftpFilesystem  bug

### ISSUE THREAD

**Issue by zhangxingcun** [creocoder/yii2-flysystem#6]
71 line
  if ($this->password === null || $this->privateKey === null) {
to:
  if ($this->password === null && $this->privateKey === null) {

**Comment by creocoder** [comment]
The original code is absollute correct. You can provide password **or** private key. Also look at adapter code: https://github.com/thephpleague/flysystem-sftp/blob/master/src/SftpAdapter.php#L154

**Comment by creocoder** [comment]
Sorry, seems you mean component configuration check logic.

**Comment by creocoder** [comment]
@zhangxingcun Fixed, thanks!
